### ISSUE TITLE
Frontend container unable to start

### ISSUE THREAD

**Issue by alexgutjahr** [usekaneo/kaneo#218]
Just pulled the most recent image version of the frontend (ghcr.io/usekaneo/web:latest@sha256:5452bc4b9db68c29040cfcca0e665862fa03fd3f576a9bc8e889f51edf65ffe8) and it seems unable to start.

Logs
```
/docker-entrypoint.sh: Configuration complete; ready for start up
2025/05/04 09:59:55 [notice] 1#1: using the "epoll" event method
2025/05/04 09:59:55 [notice] 1#1: nginx/1.25.5
2025/05/04 09:59:55 [notice] 1#1: built by gcc 13.2.1 20231014 (Alpine 13.2.1_git20231014) 
2025/05/04 09:59:55 [notice] 1#1: OS: Linux 6.11.0-14-generic
2025/05/04 09:59:55 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2025/05/04 09:59:55 [notice] 1#1: start worker processes
2025/05/04 09:59:55 [notice] 1#1: start worker process 41
2025/05/04 09:59:55 [notice] 1#1: start worker process 42
2025/05/04 09:59:55 [notice] 1#1: start worker process 43
2025/05/04 09:59:55 [notice] 1#1: start worker process 44
2025/05/04 09:59:55 [notice] 1#1: start worker process 45
2025/05/04 09:59:55 [notice] 1#1: start worker process 46
2025/05/04 09:59:55 [notice] 1#1: start worker process 47
2025/05/04 09:59:55 [notice] 1#1: start worker process 48
...
```

**Comment by aacevski** [comment]
Hey, can you share the logs of the backend container?

**Comment by alexgutjahr** [comment]
@aacevski good catch, logs below, assuming a duplicate of #192 

```
Migrating database...
DrizzleError: Failed to run the query 'CREATE TABLE `activity` (
	`id` text PRIMARY KEY NOT NULL,
	`task_id` text NOT NULL,
	`type` text NOT NULL,
	`created_at` integer DEFAULT '"2025-04-17T20:55:01.755Z"' NOT NULL,
	`user_email` text NOT NULL,
	`content` text,
	FOREIGN KEY (`task_id`) REFERENCES `task`(`id`) ON UPDATE cascade ON DELETE cascade,
	FOREIGN KEY (`user_email`) REFERENCES `user`(`email`) ON UPDATE cascade ON DELETE cascade
);

'
    at BetterSQLiteSession.run (/app/apps/api/dist/index.js:12162:13)
    at SQLiteSyncDialect.migrate (/app/apps/api/dist/index.js:10496:21)
    ... 4 lines matching cause stack trace ...
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  cause: SqliteError: table `activity` already exists
      at Database.prepare (/app/node_modules/.pnpm/better-sqlite3@11.9.1/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
      at BetterSQLiteSession.prepareQuery (/app/apps/api/dist/index.js:12218:30)
      at BetterSQLiteSession.prepareOneTimeQuery (/app/apps/api/dist/index.js:12155:17)
      at BetterSQLiteSession.run (/app/apps/api/dist/index.js:12160:19)
      at SQLiteSyncDialect.migrate (/app/apps/api/dist/index.js:10496:21)
      at migrate (/app/apps/api/dist/index.js:1174:15)
      at Object.<anonymous> (/app/apps/api/dist/index.js:14623:3)
      at Module._compile (node:internal/modules/cjs/loader:1369:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
      at Module.load (node:internal/modules/cjs/loader:1206:32) {
    code: 'SQLITE_ERROR'
  }

}

🏃 Hono API is running at http://localhost:1337
```

**Comment by aacevski** [comment]
Hey @alexgutjahr, I pushed some new changes to the migrations. Can you try now?

**Comment by alexgutjahr** [comment]
@aacevski backend looks good now

```
Migrating database...
🏃 Hono API is running at http://localhost:1337
```

.. but frontend still hangs:

```
Environment variable replacement complete
/docker-entrypoint.sh: Configuration complete; ready for start up
2025/05/06 04:25:09 [notice] 1#1: using the "epoll" event method
2025/05/06 04:25:09 [notice] 1#1: nginx/1.25.5
2025/05/06 04:25:09 [notice] 1#1: built by gcc 13.2.1 20231014 (Alpine 13.2.1_git20231014) 
2025/05/06 04:25:09 [notice] 1#1: OS: Linux 6.11.0-14-generic
2025/05/06 04:25:09 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2025/05/06 04:25:09 [notice] 1#1: start worker processes
2025/05/06 04:25:09 [notice] 1#1: start worker process 41
2025/05/06 04:25:09 [notice] 1#1: start worker process 42
2025/05/06 04:25:09 [notice] 1#1: start worker process 43
...
```

**Comment by aacevski** [comment]
Hey! I have migrated Kaneo to something more stable. It's currently using Postgres and I've seen no issues for now. It was quite unstable during the beta but now it should be better. I will close this for now - if the issue persists don't hesitate to let me know. Thank you so much!
